# Generated by Django 5.1.4 on 2024-12-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='student',
            name='images',
            field=models.ImageField(upload_to='i mages/'),
        ),
    ]
