# Generated by Django 5.1.4 on 2024-12-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_deleted',
        ),
    ]
