# Generated by Django 5.1.4 on 2025-01-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_is_deleted'),
        ('teachers', '0008_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='class_leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='teachers.teacher'),
        ),
    ]
